name: Test GitHub Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Secrets Availability
      run: |
        echo "=== Testing GitHub Secrets ==="
        echo "GCP_PROJECT_ID is set: ${{ secrets.GCP_PROJECT_ID != '' }}"
        echo "GCP_SA_KEY is set: ${{ secrets.GCP_SA_KEY != '' }}"
        echo "VITE_SUPABASE_URL is set: ${{ secrets.VITE_SUPABASE_URL != '' }}"
        echo "VITE_SUPABASE_ANON_KEY is set: ${{ secrets.VITE_SUPABASE_ANON_KEY != '' }}"
        
        if [ "${{ secrets.GCP_PROJECT_ID }}" = "" ]; then
          echo "❌ GCP_PROJECT_ID is not set"
          exit 1
        fi
        
        if [ "${{ secrets.GCP_SA_KEY }}" = "" ]; then
          echo "❌ GCP_SA_KEY is not set"
          exit 1
        fi
        
        if [ "${{ secrets.VITE_SUPABASE_URL }}" = "" ]; then
          echo "❌ VITE_SUPABASE_URL is not set"
          exit 1
        fi
        
        if [ "${{ secrets.VITE_SUPABASE_ANON_KEY }}" = "" ]; then
          echo "❌ VITE_SUPABASE_ANON_KEY is not set"
          exit 1
        fi
        
        echo "✅ All required secrets are set"
        
    - name: Test Google Cloud Authentication
      if: secrets.GCP_PROJECT_ID != '' && secrets.GCP_SA_KEY != ''
      run: |
        echo "=== Testing Google Cloud Authentication ==="
        
        # Setup Google Cloud CLI
        echo "${{ secrets.GCP_SA_KEY }}" > /tmp/service-account-key.json
        
        # Authenticate with service account
        gcloud auth activate-service-account --key-file=/tmp/service-account-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        
        # Test authentication
        echo "Current project: $(gcloud config get-value project)"
        echo "Current account: $(gcloud config get-value account)"
        gcloud auth list
        
        # Test basic command
        gcloud projects describe ${{ secrets.GCP_PROJECT_ID }} --format="value(projectId)"
        
        echo "✅ Google Cloud authentication successful"
        
        # Clean up
        rm /tmp/service-account-key.json 